package com.lee.oam.pojo;

import java.io.Serializable;

public class OamAppUser implements Serializable {
    /**
     * 主键
     *
     * @mbg.generated 2017-03-06 13:56:40
     */
    private String id;

    /**
     * 关联appID
     *
     * @mbg.generated 2017-03-06 13:56:40
     */
    private String appId;

    /**
     * 登录名称
     *
     * @mbg.generated 2017-03-06 13:56:40
     */
    private String loginName;

    /**
     * 登录密码
     *
     * @mbg.generated 2017-03-06 13:56:40
     */
    private String loginPassword;

    /**
     * 角色
     *
     * @mbg.generated 2017-03-06 13:56:40
     */
    private String role;

    /**
     * 是否可用
     *
     * @mbg.generated 2017-03-06 13:56:40
     */
    private String enable;
    private String enableTitle;
    /**
     * 备注
     *
     * @mbg.generated 2017-03-06 13:56:40
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table oam_app_user
     *
     * @mbg.generated 2017-03-06 13:56:40
     */
    private static final long serialVersionUID = 1L;

    /**
     * 主键
     *
     * @mbg.generated 2017-03-06 13:56:40
     */
    public String getId() {
        return id;
    }

    /**
     * 主键
     *
     * @param id java.lang.String
     *
     * @mbg.generated 2017-03-06 13:56:40
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * 关联appID
     *
     * @mbg.generated 2017-03-06 13:56:40
     */
    public String getAppId() {
        return appId;
    }

    /**
     * 关联appID
     *
     * @param appId java.lang.String
     *
     * @mbg.generated 2017-03-06 13:56:40
     */
    public void setAppId(String appId) {
        this.appId = appId == null ? null : appId.trim();
    }

    /**
     * 登录名称
     *
     * @mbg.generated 2017-03-06 13:56:40
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * 登录名称
     *
     * @param loginName java.lang.String
     *
     * @mbg.generated 2017-03-06 13:56:40
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName == null ? null : loginName.trim();
    }

    /**
     * 登录密码
     *
     * @mbg.generated 2017-03-06 13:56:40
     */
    public String getLoginPassword() {
        return loginPassword;
    }

    /**
     * 登录密码
     *
     * @param loginPassword java.lang.String
     *
     * @mbg.generated 2017-03-06 13:56:40
     */
    public void setLoginPassword(String loginPassword) {
        this.loginPassword = loginPassword == null ? null : loginPassword.trim();
    }

    /**
     * 角色
     *
     * @mbg.generated 2017-03-06 13:56:40
     */
    public String getRole() {
        return role;
    }

    /**
     * 角色
     *
     * @param role java.lang.String
     *
     * @mbg.generated 2017-03-06 13:56:40
     */
    public void setRole(String role) {
        this.role = role == null ? null : role.trim();
    }

    /**
     * 是否可用
     *
     * @mbg.generated 2017-03-06 13:56:40
     */
    public String getEnable() {
        return enable;
    }

    /**
     * 是否可用
     *
     * @param enable java.lang.String
     *
     * @mbg.generated 2017-03-06 13:56:40
     */
    public void setEnable(String enable) {
        this.enable = enable == null ? null : enable.trim();
    }

    /**
     * 备注
     *
     * @mbg.generated 2017-03-06 13:56:40
     */
    public String getRemark() {
        return remark;
    }

    /**
     * 备注
     *
     * @param remark java.lang.String
     *
     * @mbg.generated 2017-03-06 13:56:40
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

	public String getEnableTitle() {
		return enableTitle;
	}

	public void setEnableTitle(String enableTitle) {
		this.enableTitle = enableTitle;
	}
    
    
}