package com.lee.oam.pojo;

import java.io.Serializable;

import org.apache.commons.lang3.StringUtils;

public class OamApp implements Serializable {
    /**
     * 主键
     *
     * @mbg.generated 2017-02-28 17:38:39
     */
    private String id;

    /**
     * 应用全名
     *
     * @mbg.generated 2017-02-28 17:38:39
     */
    private String fullName;

    /**
     * 应用�?��
     *
     * @mbg.generated 2017-02-28 17:38:39
     */
    private String simpleName;

    /**
     * 拼音
     *
     * @mbg.generated 2017-02-28 17:38:39
     */
    private String pinyin;

    /**
     * 访问域名
     *
     * @mbg.generated 2017-02-28 17:38:39
     */
    private String domainId;
    private String domainName;

    /**
     * 生产环境 或�? 测试环境
     *
     * @mbg.generated 2017-02-28 17:38:39
     */
    private String useEvn;
    private String useEvnTitle;

    /**
     * 备注
     *
     * @mbg.generated 2017-02-28 17:38:39
     */
    private String remark;

    private String createUser;

    private String createTime;

    private String updateUser;

    private String updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table oam_app
     *
     * @mbg.generated 2017-02-28 17:38:39
     */
    private static final long serialVersionUID = 1L;

    /**
     * 主键
     *
     * @mbg.generated 2017-02-28 17:38:39
     */
    public String getId() {
        return id;
    }

    /**
     * 主键
     *
     * @param id java.lang.String
     *
     * @mbg.generated 2017-02-28 17:38:39
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * 应用全名
     *
     * @mbg.generated 2017-02-28 17:38:39
     */
    public String getFullName() {
        return fullName;
    }

    /**
     * 应用全名
     *
     * @param fullName java.lang.String
     *
     * @mbg.generated 2017-02-28 17:38:39
     */
    public void setFullName(String fullName) {
        this.fullName = fullName == null ? null : fullName.trim();
    }

    /**
     * 应用�?��
     *
     * @mbg.generated 2017-02-28 17:38:39
     */
    public String getSimpleName() {
        return simpleName;
    }

    /**
     * 应用�?��
     *
     * @param simpleName java.lang.String
     *
     * @mbg.generated 2017-02-28 17:38:39
     */
    public void setSimpleName(String simpleName) {
        this.simpleName = simpleName == null ? null : simpleName.trim();
    }

    /**
     * 拼音
     *
     * @mbg.generated 2017-02-28 17:38:39
     */
    public String getPinyin() {
        return pinyin;
    }

    /**
     * 拼音
     *
     * @param pinyin java.lang.String
     *
     * @mbg.generated 2017-02-28 17:38:39
     */
    public void setPinyin(String pinyin) {
        this.pinyin = pinyin == null ? null : pinyin.trim();
    }

    /**
     * 访问域名
     *
     * @mbg.generated 2017-02-28 17:38:39
     */
    public String getDomainId() {
        return domainId;
    }

    /**
     * 访问域名
     *
     * @param domainId java.lang.String
     *
     * @mbg.generated 2017-02-28 17:38:39
     */
    public void setDomainId(String domainId) {
        this.domainId = domainId == null ? null : domainId.trim();
    }

    /**
     * 生产环境 或�? 测试环境
     *
     * @mbg.generated 2017-02-28 17:38:39
     */
    public String getUseEvn() {
        return useEvn;
    }

    /**
     * 生产环境 或�? 测试环境
     *
     * @param useType java.lang.String
     *
     * @mbg.generated 2017-02-28 17:38:39
     */
    public void setUseEvn(String useEvn) {
        this.useEvn = useEvn == null ? null : useEvn.trim();
    }

    /**
     * 备注
     *
     * @mbg.generated 2017-02-28 17:38:39
     */
    public String getRemark() {
        return remark;
    }

    /**
     * 备注
     *
     * @param remark java.lang.String
     *
     * @mbg.generated 2017-02-28 17:38:39
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    public String getCreateUser() {
        return createUser;
    }

    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    public String getCreateTime() {
        return createTime;
    }

    public void setCreateTime(String createTime) {
        this.createTime = StringUtils.isBlank(createTime) ? null : createTime;
    }

    public String getUpdateUser() {
        return updateUser;
    }

    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    public String getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(String updateTime) {
        this.updateTime = StringUtils.isBlank(updateTime) ? null : updateTime;
    }

	public String getUseEvnTitle() {
		return useEvnTitle;
	}

	public void setUseEvnTitle(String useEvnTitle) {
		this.useEvnTitle = useEvnTitle;
	}

	public String getDomainName() {
		return domainName;
	}

	public void setDomainName(String domainName) {
		this.domainName = domainName;
	}
    
}