package com.lee.oam.pojo;

import java.io.Serializable;

public class OamBack implements Serializable {
    private String id;

    private String name;

    private String arg;

    private Integer num;

    private String buytime;

    private String quality;

    private Integer seq;

    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table oam_back
     *
     * @mbg.generated 2017-03-09 15:52:04
     */
    private static final long serialVersionUID = 1L;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    public String getArg() {
        return arg;
    }

    public void setArg(String arg) {
        this.arg = arg == null ? null : arg.trim();
    }

    public Integer getNum() {
        return num;
    }

    public void setNum(Integer num) {
        this.num = num;
    }

    public String getBuytime() {
        return buytime;
    }

    public void setBuytime(String buytime) {
        this.buytime = buytime == null ? null : buytime.trim();
    }

    public String getQuality() {
        return quality;
    }

    public void setQuality(String quality) {
        this.quality = quality == null ? null : quality.trim();
    }

    public Integer getSeq() {
        return seq;
    }

    public void setSeq(Integer seq) {
        this.seq = seq;
    }

    public String getRemark() {
        return remark;
    }

    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}