package com.lee.oam.pojo;

import java.io.Serializable;

public class OamDeviceUser implements Serializable {
    /**
     * 主键
     *
     * @mbg.generated 2017-03-02 17:21:27
     */
    private String id;

    /**
     * 服务器ID或�?网络安全ID
     *
     * @mbg.generated 2017-03-02 17:21:27
     */
    private String deviceId;

    /**
     * 系统登录名称
     *
     * @mbg.generated 2017-03-02 17:21:27
     */
    private String loginName;

    /**
     * 登录密码
     *
     * @mbg.generated 2017-03-02 17:21:27
     */
    private String loginPassword;

    /**
     * 类型：bios密码(bipa) 操作系统密码(ospa) 网络安全设备(nspa)
     *
     * @mbg.generated 2017-03-02 17:21:27
     */
    private String type;
    private String typeTitle;
    /**
     * 是否可用
     *
     * @mbg.generated 2017-03-02 17:21:27
     */
    private String enable;
    private String enableTitle;
    /**
     * 管理地址
     *
     * @mbg.generated 2017-03-02 17:21:27
     */
    private String manageUrl;

    /**
     * 备注
     *
     * @mbg.generated 2017-03-02 17:21:27
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table oam_device_user
     *
     * @mbg.generated 2017-03-02 17:21:27
     */
    private static final long serialVersionUID = 1L;

    /**
     * 主键
     *
     * @mbg.generated 2017-03-02 17:21:27
     */
    public String getId() {
        return id;
    }

    /**
     * 主键
     *
     * @param id java.lang.String
     *
     * @mbg.generated 2017-03-02 17:21:27
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * 服务器ID或�?网络安全ID
     *
     * @mbg.generated 2017-03-02 17:21:27
     */
    public String getDeviceId() {
        return deviceId;
    }

    /**
     * 服务器ID或�?网络安全ID
     *
     * @param deviceId java.lang.String
     *
     * @mbg.generated 2017-03-02 17:21:27
     */
    public void setDeviceId(String deviceId) {
        this.deviceId = deviceId == null ? null : deviceId.trim();
    }

    /**
     * 系统登录名称
     *
     * @mbg.generated 2017-03-02 17:21:27
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * 系统登录名称
     *
     * @param loginName java.lang.String
     *
     * @mbg.generated 2017-03-02 17:21:27
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName == null ? null : loginName.trim();
    }

    /**
     * 登录密码
     *
     * @mbg.generated 2017-03-02 17:21:27
     */
    public String getLoginPassword() {
        return loginPassword;
    }

    /**
     * 登录密码
     *
     * @param loginPassword java.lang.String
     *
     * @mbg.generated 2017-03-02 17:21:27
     */
    public void setLoginPassword(String loginPassword) {
        this.loginPassword = loginPassword == null ? null : loginPassword.trim();
    }

    /**
     * 类型：bios密码(bipa) 操作系统密码(ospa) 网络安全设备(nspa)
     *
     * @mbg.generated 2017-03-02 17:21:27
     */
    public String getType() {
        return type;
    }

    /**
     * 类型：bios密码(bipa) 操作系统密码(ospa) 网络安全设备(nspa)
     *
     * @param type java.lang.String
     *
     * @mbg.generated 2017-03-02 17:21:27
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * 是否可用
     *
     * @mbg.generated 2017-03-02 17:21:27
     */
    public String getEnable() {
        return enable;
    }

    /**
     * 是否可用
     *
     * @param enable java.lang.String
     *
     * @mbg.generated 2017-03-02 17:21:27
     */
    public void setEnable(String enable) {
        this.enable = enable == null ? null : enable.trim();
    }

    /**
     * 管理地址
     *
     * @mbg.generated 2017-03-02 17:21:27
     */
    public String getManageUrl() {
        return manageUrl;
    }

    /**
     * 管理地址
     *
     * @param manageUrl java.lang.String
     *
     * @mbg.generated 2017-03-02 17:21:27
     */
    public void setManageUrl(String manageUrl) {
        this.manageUrl = manageUrl == null ? null : manageUrl.trim();
    }

    /**
     * 备注
     *
     * @mbg.generated 2017-03-02 17:21:27
     */
    public String getRemark() {
        return remark;
    }

    /**
     * 备注
     *
     * @param remark java.lang.String
     *
     * @mbg.generated 2017-03-02 17:21:27
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

	public String getTypeTitle() {
		return typeTitle;
	}

	public void setTypeTitle(String typeTitle) {
		this.typeTitle = typeTitle;
	}

	public String getEnableTitle() {
		return enableTitle;
	}

	public void setEnableTitle(String enableTitle) {
		this.enableTitle = enableTitle;
	}
    
    
}