package com.lee.oam.pojo;

import java.io.Serializable;

import org.apache.commons.lang3.StringUtils;

public class OamDomain implements Serializable {
    /**
     * 主键
     *
     * @mbg.generated 2017-03-06 15:59:10
     */
    private String id;

    /**
     * 域名�?
     *
     * @mbg.generated 2017-03-06 15:59:10
     */
    private String domainBus;

    /**
     * 域名
     *
     * @mbg.generated 2017-03-06 15:59:10
     */
    private String domain;

    /**
     * 到期时间
     *
     * @mbg.generated 2017-03-06 15:59:10
     */
    private String endTime;

    /**
     * 域名商账�?
     *
     * @mbg.generated 2017-03-06 15:59:10
     */
    private String busAccount;

    /**
     * 域名商密�?
     *
     * @mbg.generated 2017-03-06 15:59:10
     */
    private String busPassword;

    /**
     * 验证邮箱
     *
     * @mbg.generated 2017-03-06 15:59:10
     */
    private String mail;

    /**
     * 注册手机
     *
     * @mbg.generated 2017-03-06 15:59:10
     */
    private String tell;

    /**
     * 有效持有�?
     *
     * @mbg.generated 2017-03-06 15:59:10
     */
    private String ownner;

    private String remark;

    /**
     * 公网ip
     *
     * @mbg.generated 2017-03-06 15:59:10
     */
    private String ip;

    /**
     * 公网掩码
     *
     * @mbg.generated 2017-03-06 15:59:10
     */
    private String mask;

    /**
     * 公网网关
     *
     * @mbg.generated 2017-03-06 15:59:10
     */
    private String getway;

    /**
     * 占用端口
     *
     * @mbg.generated 2017-03-06 15:59:10
     */
    private Integer port;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table oam_domain
     *
     * @mbg.generated 2017-03-06 15:59:10
     */
    private static final long serialVersionUID = 1L;

    /**
     * 主键
     *
     * @mbg.generated 2017-03-06 15:59:10
     */
    public String getId() {
        return id;
    }

    /**
     * 主键
     *
     * @param id java.lang.String
     *
     * @mbg.generated 2017-03-06 15:59:10
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * 域名�?
     *
     * @mbg.generated 2017-03-06 15:59:10
     */
    public String getDomainBus() {
        return domainBus;
    }

    /**
     * 域名�?
     *
     * @param domainBus java.lang.String
     *
     * @mbg.generated 2017-03-06 15:59:10
     */
    public void setDomainBus(String domainBus) {
        this.domainBus = domainBus == null ? null : domainBus.trim();
    }

    /**
     * 域名
     *
     * @mbg.generated 2017-03-06 15:59:10
     */
    public String getDomain() {
        return domain;
    }

    /**
     * 域名
     *
     * @param domain java.lang.String
     *
     * @mbg.generated 2017-03-06 15:59:10
     */
    public void setDomain(String domain) {
        this.domain = domain == null ? null : domain.trim();
    }

    /**
     * 到期时间
     *
     * @mbg.generated 2017-03-06 15:59:10
     */
    public String getEndTime() {
        return endTime;
    }

    /**
     * 到期时间
     *
     * @param endTime java.util.Date
     *
     * @mbg.generated 2017-03-06 15:59:10
     */
    public void setEndTime(String endTime) {
        this.endTime = StringUtils.isBlank(endTime) ? null : endTime;
    }

    /**
     * 域名商账�?
     *
     * @mbg.generated 2017-03-06 15:59:10
     */
    public String getBusAccount() {
        return busAccount;
    }

    /**
     * 域名商账�?
     *
     * @param busAccount java.lang.String
     *
     * @mbg.generated 2017-03-06 15:59:10
     */
    public void setBusAccount(String busAccount) {
        this.busAccount = busAccount == null ? null : busAccount.trim();
    }

    /**
     * 域名商密�?
     *
     * @mbg.generated 2017-03-06 15:59:10
     */
    public String getBusPassword() {
        return busPassword;
    }

    /**
     * 域名商密�?
     *
     * @param busPassword java.lang.String
     *
     * @mbg.generated 2017-03-06 15:59:10
     */
    public void setBusPassword(String busPassword) {
        this.busPassword = busPassword == null ? null : busPassword.trim();
    }

    /**
     * 验证邮箱
     *
     * @mbg.generated 2017-03-06 15:59:10
     */
    public String getMail() {
        return mail;
    }

    /**
     * 验证邮箱
     *
     * @param mail java.lang.String
     *
     * @mbg.generated 2017-03-06 15:59:10
     */
    public void setMail(String mail) {
        this.mail = mail == null ? null : mail.trim();
    }

    /**
     * 注册手机
     *
     * @mbg.generated 2017-03-06 15:59:10
     */
    public String getTell() {
        return tell;
    }

    /**
     * 注册手机
     *
     * @param tell java.lang.String
     *
     * @mbg.generated 2017-03-06 15:59:10
     */
    public void setTell(String tell) {
        this.tell = tell == null ? null : tell.trim();
    }

    /**
     * 有效持有�?
     *
     * @mbg.generated 2017-03-06 15:59:10
     */
    public String getOwnner() {
        return ownner;
    }

    /**
     * 有效持有�?
     *
     * @param ownner java.lang.String
     *
     * @mbg.generated 2017-03-06 15:59:10
     */
    public void setOwnner(String ownner) {
        this.ownner = ownner == null ? null : ownner.trim();
    }

    public String getRemark() {
        return remark;
    }

    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * 公网ip
     *
     * @mbg.generated 2017-03-06 15:59:10
     */
    public String getIp() {
        return ip;
    }

    /**
     * 公网ip
     *
     * @param ip java.lang.String
     *
     * @mbg.generated 2017-03-06 15:59:10
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * 公网掩码
     *
     * @mbg.generated 2017-03-06 15:59:10
     */
    public String getMask() {
        return mask;
    }

    /**
     * 公网掩码
     *
     * @param mask java.lang.String
     *
     * @mbg.generated 2017-03-06 15:59:10
     */
    public void setMask(String mask) {
        this.mask = mask == null ? null : mask.trim();
    }

    /**
     * 公网网关
     *
     * @mbg.generated 2017-03-06 15:59:10
     */
    public String getGetway() {
        return getway;
    }

    /**
     * 公网网关
     *
     * @param getway java.lang.String
     *
     * @mbg.generated 2017-03-06 15:59:10
     */
    public void setGetway(String getway) {
        this.getway = getway == null ? null : getway.trim();
    }

    /**
     * 占用端口
     *
     * @mbg.generated 2017-03-06 15:59:10
     */
    public Integer getPort() {
        return port;
    }

    /**
     * 占用端口
     *
     * @param port java.lang.Integer
     *
     * @mbg.generated 2017-03-06 15:59:10
     */
    public void setPort(Integer port) {
        this.port = port;
    }
}