package com.lee.oam.pojo;

import java.io.Serializable;
import java.util.List;

import org.apache.commons.lang3.StringUtils;

/**
 * 服务器硬件基础信息表
 * @author Administrator
 *
 */
public class OamDevice implements Serializable {
    /**
     * 主键
     *
     * @mbg.generated 2017-02-27 10:04:58
     */
    private String id;

    /**
     * 设备序列�?
     *
     * @mbg.generated 2017-02-27 10:04:58
     */
    private String serialNo;

    /**
     * 固定资产编号
     *
     * @mbg.generated 2017-02-27 10:04:58
     */
    private String fixedNo;

    /**
     * 设备名称
     *
     * @mbg.generated 2017-02-27 10:04:58
     */
    private String name;

    /**
     * 厂商
     *
     * @mbg.generated 2017-02-27 10:04:58
     */
    private String manufacturer;

    /**
     * 型号
     *
     * @mbg.generated 2017-02-27 10:04:58
     */
    private String model;

    /**
     * 位置
     *
     * @mbg.generated 2017-02-27 10:04:58
     */
    private String position;

    /**
     * 尺寸
     *
     * @mbg.generated 2017-02-27 10:04:58
     */
    private Integer size;

    /**
     * 类型：服务器硬件 (yj) 虚拟�?xlj) 阿里�?aly) 网络和安�?ns)
     *
     * @mbg.generated 2017-02-27 10:04:58
     */
    private String type;
    private String typeTitle;
    /**
     * 宿主机，供虚拟机使用
     *
     * @mbg.generated 2017-02-27 10:04:58
     */
    private String hostId;
    private String hostSerialNo;
    /**
     * 网络或安全设备类�?
     *
     * @mbg.generated 2017-02-27 10:04:58
     */
    private String nsType;

    /**
     * 使用部门
     *
     * @mbg.generated 2017-02-27 10:04:58
     */
    private String deptId;
    private String deptName;

    /**
     * 光口数量
     *
     * @mbg.generated 2017-02-27 10:04:58
     */
    private Integer rxnNum;

    /**
     * 管理网口数量
     *
     * @mbg.generated 2017-02-27 10:04:58
     */
    private Integer taNum;

    /**
     * console口数�?
     *
     * @mbg.generated 2017-02-27 10:04:58
     */
    private Integer cosNum;

    /**
     * lan口数�?
     *
     * @mbg.generated 2017-02-27 10:04:58
     */
    private Integer lanNum;

    /**
     * 使用情况
     *
     * @mbg.generated 2017-02-27 10:04:58
     */
    private String useContition;
    private String useContitionTitle;
    /**
     * 购入日期
     *
     * @mbg.generated 2017-02-27 10:04:58
     */
    private String buyTime;

    /**
     * 过保日期
     *
     * @mbg.generated 2017-02-27 10:04:58
     */
    private String overTime;

    /**
     * 操作系统
     *
     * @mbg.generated 2017-02-27 10:04:58
     */
    private String os;

    /**
     * 操作系统是否正版
     *
     * @mbg.generated 2017-02-27 10:04:58
     */
    private String osLegal;
    private String osLegalTitle;

    /**
     * 主机或�?备机
     *
     * @mbg.generated 2017-02-27 10:04:58
     */
    private String useType;
    private String useTypeTitle;

    /**
     * 备注
     *
     * @mbg.generated 2017-02-27 10:04:58
     */
    private String remark;

    private String createUser;

    private String createTime;

    private String updateUser;

    private String updateTime;

    private OamDeviceAttr deviceAttr;
    private List<OamIp> ips;
    /**虚拟机宿主机*/
    private OamDevice host;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table oam_device
     *
     * @mbg.generated 2017-02-27 10:04:58
     */
    private static final long serialVersionUID = 1L;

    /**
     * 主键
     *
     * @mbg.generated 2017-02-27 10:04:58
     */
    public String getId() {
        return id;
    }

    /**
     * 主键
     *
     * @param id java.lang.String
     *
     * @mbg.generated 2017-02-27 10:04:58
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * 设备序列�?
     *
     * @mbg.generated 2017-02-27 10:04:58
     */
    public String getSerialNo() {
        return serialNo;
    }

    /**
     * 设备序列�?
     *
     * @param serialNo java.lang.String
     *
     * @mbg.generated 2017-02-27 10:04:58
     */
    public void setSerialNo(String serialNo) {
        this.serialNo = serialNo == null ? null : serialNo.trim();
    }

    /**
     * 固定资产编号
     *
     * @mbg.generated 2017-02-27 10:04:58
     */
    public String getFixedNo() {
        return fixedNo;
    }

    /**
     * 固定资产编号
     *
     * @param fixedNo java.lang.String
     *
     * @mbg.generated 2017-02-27 10:04:58
     */
    public void setFixedNo(String fixedNo) {
        this.fixedNo = fixedNo == null ? null : fixedNo.trim();
    }

    /**
     * 设备名称
     *
     * @mbg.generated 2017-02-27 10:04:58
     */
    public String getName() {
        return name;
    }

    /**
     * 设备名称
     *
     * @param name java.lang.String
     *
     * @mbg.generated 2017-02-27 10:04:58
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * 厂商
     *
     * @mbg.generated 2017-02-27 10:04:58
     */
    public String getManufacturer() {
        return manufacturer;
    }

    /**
     * 厂商
     *
     * @param manufacturer java.lang.String
     *
     * @mbg.generated 2017-02-27 10:04:58
     */
    public void setManufacturer(String manufacturer) {
        this.manufacturer = manufacturer == null ? null : manufacturer.trim();
    }

    /**
     * 型号
     *
     * @mbg.generated 2017-02-27 10:04:58
     */
    public String getModel() {
        return model;
    }

    /**
     * 型号
     *
     * @param model java.lang.String
     *
     * @mbg.generated 2017-02-27 10:04:58
     */
    public void setModel(String model) {
        this.model = model == null ? null : model.trim();
    }

    /**
     * 位置
     *
     * @mbg.generated 2017-02-27 10:04:58
     */
    public String getPosition() {
        return position;
    }

    /**
     * 位置
     *
     * @param position java.lang.String
     *
     * @mbg.generated 2017-02-27 10:04:58
     */
    public void setPosition(String position) {
        this.position = position == null ? null : position.trim();
    }

    /**
     * 尺寸
     *
     * @mbg.generated 2017-02-27 10:04:58
     */
    public Integer getSize() {
        return size;
    }

    /**
     * 尺寸
     *
     * @param size java.lang.Integer
     *
     * @mbg.generated 2017-02-27 10:04:58
     */
    public void setSize(Integer size) {
        this.size = size;
    }

    /**
     * 类型：服务器硬件 (yj) 虚拟�?xlj) 阿里�?aly) 网络和安�?ns)
     *
     * @mbg.generated 2017-02-27 10:04:58
     */
    public String getType() {
        return type;
    }

    /**
     * 类型：服务器硬件 (yj) 虚拟�?xlj) 阿里�?aly) 网络和安�?ns)
     *
     * @param type java.lang.String
     *
     * @mbg.generated 2017-02-27 10:04:58
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * 宿主机，供虚拟机使用
     *
     * @mbg.generated 2017-02-27 10:04:58
     */
    public String getHostId() {
        return hostId;
    }

    /**
     * 宿主机，供虚拟机使用
     *
     * @param hostId java.lang.String
     *
     * @mbg.generated 2017-02-27 10:04:58
     */
    public void setHostId(String hostId) {
        this.hostId = hostId == null ? null : hostId.trim();
    }

    /**
     * 网络或安全设备类�?
     *
     * @mbg.generated 2017-02-27 10:04:58
     */
    public String getNsType() {
        return nsType;
    }

    /**
     * 网络或安全设备类�?
     *
     * @param nsType java.lang.String
     *
     * @mbg.generated 2017-02-27 10:04:58
     */
    public void setNsType(String nsType) {
        this.nsType = nsType == null ? null : nsType.trim();
    }

    /**
     * 使用部门
     *
     * @mbg.generated 2017-02-27 10:04:58
     */
    public String getDeptId() {
        return deptId;
    }

    /**
     * 使用部门
     *
     * @param deptId java.lang.String
     *
     * @mbg.generated 2017-02-27 10:04:58
     */
    public void setDeptId(String deptId) {
        this.deptId = deptId == null ? null : deptId.trim();
    }

    /**
     * 光口数量
     *
     * @mbg.generated 2017-02-27 10:04:58
     */
    public Integer getRxnNum() {
        return rxnNum;
    }

    /**
     * 光口数量
     *
     * @param rxnNum java.lang.Integer
     *
     * @mbg.generated 2017-02-27 10:04:58
     */
    public void setRxnNum(Integer rxnNum) {
        this.rxnNum = rxnNum;
    }

    /**
     * 管理网口数量
     *
     * @mbg.generated 2017-02-27 10:04:58
     */
    public Integer getTaNum() {
        return taNum;
    }

    /**
     * 管理网口数量
     *
     * @param taNum java.lang.Integer
     *
     * @mbg.generated 2017-02-27 10:04:58
     */
    public void setTaNum(Integer taNum) {
        this.taNum = taNum;
    }

    /**
     * console口数�?
     *
     * @mbg.generated 2017-02-27 10:04:58
     */
    public Integer getCosNum() {
        return cosNum;
    }

    /**
     * console口数�?
     *
     * @param cosNum java.lang.Integer
     *
     * @mbg.generated 2017-02-27 10:04:58
     */
    public void setCosNum(Integer cosNum) {
        this.cosNum = cosNum;
    }

    /**
     * lan口数�?
     *
     * @mbg.generated 2017-02-27 10:04:58
     */
    public Integer getLanNum() {
        return lanNum;
    }

    /**
     * lan口数�?
     *
     * @param lanNum java.lang.Integer
     *
     * @mbg.generated 2017-02-27 10:04:58
     */
    public void setLanNum(Integer lanNum) {
        this.lanNum = lanNum;
    }

    /**
     * 使用情况
     *
     * @mbg.generated 2017-02-27 10:04:58
     */
    public String getUseContition() {
        return useContition;
    }

    /**
     * 使用情况
     *
     * @param use java.lang.String
     *
     * @mbg.generated 2017-02-27 10:04:58
     */
    public void setUseContition(String useContition) {
        this.useContition = useContition == null ? null : useContition.trim();
    }

    /**
     * 购入日期
     *
     * @mbg.generated 2017-02-27 10:04:58
     */
    public String getBuyTime() {
        return buyTime;
    }

    /**
     * 购入日期
     *
     * @param buyTime java.util.Date
     *
     * @mbg.generated 2017-02-27 10:04:58
     */
    public void setBuyTime(String buyTime) {
        this.buyTime =  StringUtils.isBlank(buyTime) ? null : buyTime;
    }

    /**
     * 过保日期
     *
     * @mbg.generated 2017-02-27 10:04:58
     */
    public String getOverTime() {
        return overTime;
    }

    /**
     * 过保日期
     *
     * @param overTime java.util.Date
     *
     * @mbg.generated 2017-02-27 10:04:58
     */
    public void setOverTime(String overTime) {
        this.overTime =  StringUtils.isBlank(overTime) ? null : overTime;
    }

    /**
     * 操作系统
     *
     * @mbg.generated 2017-02-27 10:04:58
     */
    public String getOs() {
        return os;
    }

    /**
     * 操作系统
     *
     * @param os java.lang.String
     *
     * @mbg.generated 2017-02-27 10:04:58
     */
    public void setOs(String os) {
        this.os = os == null ? null : os.trim();
    }

    /**
     * 操作系统是否正版
     *
     * @mbg.generated 2017-02-27 10:04:58
     */
    public String getOsLegal() {
        return osLegal;
    }

    /**
     * 操作系统是否正版
     *
     * @param osLegal java.lang.String
     *
     * @mbg.generated 2017-02-27 10:04:58
     */
    public void setOsLegal(String osLegal) {
        this.osLegal = osLegal == null ? null : osLegal.trim();
    }

    /**
     * 主机或�?备机
     *
     * @mbg.generated 2017-02-27 10:04:58
     */
    public String getUseType() {
        return useType;
    }

    /**
     * 主机或�?备机
     *
     * @param useType java.lang.String
     *
     * @mbg.generated 2017-02-27 10:04:58
     */
    public void setUseType(String useType) {
        this.useType = useType == null ? null : useType.trim();
    }

    /**
     * 备注
     *
     * @mbg.generated 2017-02-27 10:04:58
     */
    public String getRemark() {
        return remark;
    }

    /**
     * 备注
     *
     * @param remark java.lang.String
     *
     * @mbg.generated 2017-02-27 10:04:58
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    public String getCreateUser() {
        return createUser;
    }

    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    public String getCreateTime() {
        return createTime;
    }

    public void setCreateTime(String createTime) {
        this.createTime = StringUtils.isBlank(createTime) ? null : createTime;
    }

    public String getUpdateUser() {
        return updateUser;
    }

    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    public String getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(String updateTime) {
        this.updateTime = StringUtils.isBlank(updateTime) ? null : updateTime;
    }

	public OamDeviceAttr getDeviceAttr() {
		return deviceAttr;
	}

	public void setDeviceAttr(OamDeviceAttr deviceAttr) {
		this.deviceAttr = deviceAttr;
	}

	public String getTypeTitle() {
		return typeTitle;
	}

	public void setTypeTitle(String typeTitle) {
		this.typeTitle = typeTitle;
	}

	public String getDeptName() {
		return deptName;
	}

	public void setDeptName(String deptName) {
		this.deptName = deptName;
	}

	public String getUseContitionTitle() {
		return useContitionTitle;
	}

	public void setUseContitionTitle(String useContitionTitle) {
		this.useContitionTitle = useContitionTitle;
	}

	public String getOsLegalTitle() {
		return osLegalTitle;
	}

	public void setOsLegalTitle(String osLegalTitle) {
		this.osLegalTitle = osLegalTitle;
	}

	public String getUseTypeTitle() {
		return useTypeTitle;
	}

	public void setUseTypeTitle(String useTypeTitle) {
		this.useTypeTitle = useTypeTitle;
	}

	public String getHostSerialNo() {
		return hostSerialNo;
	}

	public void setHostSerialNo(String hostSerialNo) {
		this.hostSerialNo = hostSerialNo;
	}

	public List<OamIp> getIps() {
		return ips;
	}

	public void setIps(List<OamIp> ips) {
		this.ips = ips;
	}

	public OamDevice getHost() {
		return host;
	}

	public void setHost(OamDevice host) {
		this.host = host;
	}
    
}