package com.lee.oam.pojo;

import java.io.Serializable;

/**
 * 设备属性
 * @author Administrator
 *
 */
public class OamDeviceAttr implements Serializable {
    /**
     * 主键
     *
     * @mbg.generated 2017-02-27 10:16:35
     */
    private String id;

    /**
     * 设备ID
     *
     * @mbg.generated 2017-02-27 10:16:35
     */
    private String deviceId;

    /**
     * cpu型号
     *
     * @mbg.generated 2017-02-27 10:16:35
     */
    private String cpuModel;

    /**
     * cpu数量
     *
     * @mbg.generated 2017-02-27 10:16:35
     */
    private Integer cpuNum;

    /**
     * 磁盘品牌
     *
     * @mbg.generated 2017-02-27 10:16:35
     */
    private String diskBrand;

    /**
     * 磁盘型号
     *
     * @mbg.generated 2017-02-27 10:16:35
     */
    private String diskModel;

    /**
     * 磁盘容量
     *
     * @mbg.generated 2017-02-27 10:16:35
     */
    private Integer diskCapacity;

    /**
     * 磁盘尺寸
     *
     * @mbg.generated 2017-02-27 10:16:35
     */
    private Float diskSize;

    /**
     * 磁盘转�?
     *
     * @mbg.generated 2017-02-27 10:16:35
     */
    private Integer diskConvolution;

    /**
     * 磁盘阵列卡型�?
     *
     * @mbg.generated 2017-02-27 10:16:35
     */
    private String diskRaidModel;

    /**
     * 磁盘阵列类型
     *
     * @mbg.generated 2017-02-27 10:16:35
     */
    private String diskRaidType;

    /**
     * 磁盘数量
     *
     * @mbg.generated 2017-02-27 10:16:35
     */
    private Integer diskNum;

    /**
     * 内存品牌
     *
     * @mbg.generated 2017-02-27 10:16:35
     */
    private String ramBrand;

    /**
     * 内存型号
     *
     * @mbg.generated 2017-02-27 10:16:35
     */
    private String ramModel;

    /**
     * 内存代数
     *
     * @mbg.generated 2017-02-27 10:16:35
     */
    private String ramDdr;

    /**
     * 内存容量
     *
     * @mbg.generated 2017-02-27 10:16:35
     */
    private Integer ramCapacity;

    /**
     * 内存频率
     *
     * @mbg.generated 2017-02-27 10:16:35
     */
    private Integer ramHz;

    /**
     * 内存数量
     *
     * @mbg.generated 2017-02-27 10:16:35
     */
    private Integer ramNum;

    /**
     * 网口带宽
     *
     * @mbg.generated 2017-02-27 10:16:35
     */
    private Integer nmBand;

    /**
     * 网口数量
     *
     * @mbg.generated 2017-02-27 10:16:35
     */
    private Integer nmNum;

    /**
     * 电源功率
     *
     * @mbg.generated 2017-02-27 10:16:35
     */
    private Integer powerKw;

    /**
     * 电源数量
     *
     * @mbg.generated 2017-02-27 10:16:35
     */
    private Integer powerNum;

    /**
     * 备注
     *
     * @mbg.generated 2017-02-27 10:16:35
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table oam_device_attr
     *
     * @mbg.generated 2017-02-27 10:16:35
     */
    private static final long serialVersionUID = 1L;

    /**
     * 主键
     *
     * @mbg.generated 2017-02-27 10:16:35
     */
    public String getId() {
        return id;
    }

    /**
     * 主键
     *
     * @param id java.lang.String
     *
     * @mbg.generated 2017-02-27 10:16:35
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * 设备ID
     *
     * @mbg.generated 2017-02-27 10:16:35
     */
    public String getDeviceId() {
        return deviceId;
    }

    /**
     * 设备ID
     *
     * @param deviceId java.lang.String
     *
     * @mbg.generated 2017-02-27 10:16:35
     */
    public void setDeviceId(String deviceId) {
        this.deviceId = deviceId == null ? null : deviceId.trim();
    }

    /**
     * cpu型号
     *
     * @mbg.generated 2017-02-27 10:16:35
     */
    public String getCpuModel() {
        return cpuModel;
    }

    /**
     * cpu型号
     *
     * @param cpuModel java.lang.String
     *
     * @mbg.generated 2017-02-27 10:16:35
     */
    public void setCpuModel(String cpuModel) {
        this.cpuModel = cpuModel == null ? null : cpuModel.trim();
    }

    /**
     * cpu数量
     *
     * @mbg.generated 2017-02-27 10:16:35
     */
    public Integer getCpuNum() {
        return cpuNum;
    }

    /**
     * cpu数量
     *
     * @param cpuNum java.lang.Integer
     *
     * @mbg.generated 2017-02-27 10:16:35
     */
    public void setCpuNum(Integer cpuNum) {
        this.cpuNum = cpuNum;
    }

    /**
     * 磁盘品牌
     *
     * @mbg.generated 2017-02-27 10:16:35
     */
    public String getDiskBrand() {
        return diskBrand;
    }

    /**
     * 磁盘品牌
     *
     * @param diskBrand java.lang.String
     *
     * @mbg.generated 2017-02-27 10:16:35
     */
    public void setDiskBrand(String diskBrand) {
        this.diskBrand = diskBrand == null ? null : diskBrand.trim();
    }

    /**
     * 磁盘型号
     *
     * @mbg.generated 2017-02-27 10:16:35
     */
    public String getDiskModel() {
        return diskModel;
    }

    /**
     * 磁盘型号
     *
     * @param diskModel java.lang.String
     *
     * @mbg.generated 2017-02-27 10:16:35
     */
    public void setDiskModel(String diskModel) {
        this.diskModel = diskModel == null ? null : diskModel.trim();
    }

    /**
     * 磁盘容量
     *
     * @mbg.generated 2017-02-27 10:16:35
     */
    public Integer getDiskCapacity() {
        return diskCapacity;
    }

    /**
     * 磁盘容量
     *
     * @param diskCapacity java.lang.Integer
     *
     * @mbg.generated 2017-02-27 10:16:35
     */
    public void setDiskCapacity(Integer diskCapacity) {
        this.diskCapacity = diskCapacity;
    }

    /**
     * 磁盘尺寸
     *
     * @mbg.generated 2017-02-27 10:16:35
     */
    public Float getDiskSize() {
        return diskSize;
    }

    /**
     * 磁盘尺寸
     *
     * @param diskSize java.lang.Float
     *
     * @mbg.generated 2017-02-27 10:16:35
     */
    public void setDiskSize(Float diskSize) {
        this.diskSize = diskSize;
    }

    /**
     * 磁盘转�?
     *
     * @mbg.generated 2017-02-27 10:16:35
     */
    public Integer getDiskConvolution() {
        return diskConvolution;
    }

    /**
     * 磁盘转�?
     *
     * @param diskConvolution java.lang.Integer
     *
     * @mbg.generated 2017-02-27 10:16:35
     */
    public void setDiskConvolution(Integer diskConvolution) {
        this.diskConvolution = diskConvolution;
    }

    /**
     * 磁盘阵列卡型�?
     *
     * @mbg.generated 2017-02-27 10:16:35
     */
    public String getDiskRaidModel() {
        return diskRaidModel;
    }

    /**
     * 磁盘阵列卡型�?
     *
     * @param diskRaidModel java.lang.String
     *
     * @mbg.generated 2017-02-27 10:16:35
     */
    public void setDiskRaidModel(String diskRaidModel) {
        this.diskRaidModel = diskRaidModel == null ? null : diskRaidModel.trim();
    }

    /**
     * 磁盘阵列类型
     *
     * @mbg.generated 2017-02-27 10:16:35
     */
    public String getDiskRaidType() {
        return diskRaidType;
    }

    /**
     * 磁盘阵列类型
     *
     * @param diskRaidType java.lang.String
     *
     * @mbg.generated 2017-02-27 10:16:35
     */
    public void setDiskRaidType(String diskRaidType) {
        this.diskRaidType = diskRaidType == null ? null : diskRaidType.trim();
    }

    /**
     * 磁盘数量
     *
     * @mbg.generated 2017-02-27 10:16:35
     */
    public Integer getDiskNum() {
        return diskNum;
    }

    /**
     * 磁盘数量
     *
     * @param diskNum java.lang.Integer
     *
     * @mbg.generated 2017-02-27 10:16:35
     */
    public void setDiskNum(Integer diskNum) {
        this.diskNum = diskNum;
    }

    /**
     * 内存品牌
     *
     * @mbg.generated 2017-02-27 10:16:35
     */
    public String getRamBrand() {
        return ramBrand;
    }

    /**
     * 内存品牌
     *
     * @param ramBrand java.lang.String
     *
     * @mbg.generated 2017-02-27 10:16:35
     */
    public void setRamBrand(String ramBrand) {
        this.ramBrand = ramBrand == null ? null : ramBrand.trim();
    }

    /**
     * 内存型号
     *
     * @mbg.generated 2017-02-27 10:16:35
     */
    public String getRamModel() {
        return ramModel;
    }

    /**
     * 内存型号
     *
     * @param ramModel java.lang.String
     *
     * @mbg.generated 2017-02-27 10:16:35
     */
    public void setRamModel(String ramModel) {
        this.ramModel = ramModel == null ? null : ramModel.trim();
    }

    /**
     * 内存代数
     *
     * @mbg.generated 2017-02-27 10:16:35
     */
    public String getRamDdr() {
        return ramDdr;
    }

    /**
     * 内存代数
     *
     * @param ramDdr java.lang.String
     *
     * @mbg.generated 2017-02-27 10:16:35
     */
    public void setRamDdr(String ramDdr) {
        this.ramDdr = ramDdr == null ? null : ramDdr.trim();
    }

    /**
     * 内存容量
     *
     * @mbg.generated 2017-02-27 10:16:35
     */
    public Integer getRamCapacity() {
        return ramCapacity;
    }

    /**
     * 内存容量
     *
     * @param ramCapacity java.lang.Integer
     *
     * @mbg.generated 2017-02-27 10:16:35
     */
    public void setRamCapacity(Integer ramCapacity) {
        this.ramCapacity = ramCapacity;
    }

    /**
     * 内存频率
     *
     * @mbg.generated 2017-02-27 10:16:35
     */
    public Integer getRamHz() {
        return ramHz;
    }

    /**
     * 内存频率
     *
     * @param ramHz java.lang.Integer
     *
     * @mbg.generated 2017-02-27 10:16:35
     */
    public void setRamHz(Integer ramHz) {
        this.ramHz = ramHz;
    }

    /**
     * 内存数量
     *
     * @mbg.generated 2017-02-27 10:16:35
     */
    public Integer getRamNum() {
        return ramNum;
    }

    /**
     * 内存数量
     *
     * @param ramNum java.lang.Integer
     *
     * @mbg.generated 2017-02-27 10:16:35
     */
    public void setRamNum(Integer ramNum) {
        this.ramNum = ramNum;
    }

    /**
     * 网口带宽
     *
     * @mbg.generated 2017-02-27 10:16:35
     */
    public Integer getNmBand() {
        return nmBand;
    }

    /**
     * 网口带宽
     *
     * @param nmBand java.lang.Integer
     *
     * @mbg.generated 2017-02-27 10:16:35
     */
    public void setNmBand(Integer nmBand) {
        this.nmBand = nmBand;
    }

    /**
     * 网口数量
     *
     * @mbg.generated 2017-02-27 10:16:35
     */
    public Integer getNmNum() {
        return nmNum;
    }

    /**
     * 网口数量
     *
     * @param nmNum java.lang.Integer
     *
     * @mbg.generated 2017-02-27 10:16:35
     */
    public void setNmNum(Integer nmNum) {
        this.nmNum = nmNum;
    }

    /**
     * 电源功率
     *
     * @mbg.generated 2017-02-27 10:16:35
     */
    public Integer getPowerKw() {
        return powerKw;
    }

    /**
     * 电源功率
     *
     * @param powerKw java.lang.Integer
     *
     * @mbg.generated 2017-02-27 10:16:35
     */
    public void setPowerKw(Integer powerKw) {
        this.powerKw = powerKw;
    }

    /**
     * 电源数量
     *
     * @mbg.generated 2017-02-27 10:16:35
     */
    public Integer getPowerNum() {
        return powerNum;
    }

    /**
     * 电源数量
     *
     * @param powerNum java.lang.Integer
     *
     * @mbg.generated 2017-02-27 10:16:35
     */
    public void setPowerNum(Integer powerNum) {
        this.powerNum = powerNum;
    }

    /**
     * 备注
     *
     * @mbg.generated 2017-02-27 10:16:35
     */
    public String getRemark() {
        return remark;
    }

    /**
     * 备注
     *
     * @param remark java.lang.String
     *
     * @mbg.generated 2017-02-27 10:16:35
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}