package com.lee.oam.pojo;

import java.io.Serializable;

public class OamDeviceUpgrade implements Serializable {
    private String id;

    private String deviceId;

    private String loginName;

    private String loginPassword;

    private String domain;

    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table oam_device_upgrade
     *
     * @mbg.generated 2017-03-06 10:25:10
     */
    private static final long serialVersionUID = 1L;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    public String getDeviceId() {
        return deviceId;
    }

    public void setDeviceId(String deviceId) {
        this.deviceId = deviceId == null ? null : deviceId.trim();
    }

    public String getLoginName() {
        return loginName;
    }

    public void setLoginName(String loginName) {
        this.loginName = loginName == null ? null : loginName.trim();
    }

    public String getLoginPassword() {
        return loginPassword;
    }

    public void setLoginPassword(String loginPassword) {
    	 this.loginPassword = loginPassword == null ? null : loginPassword.trim();
    }

    public String getDomain() {
        return domain;
    }

    public void setDomain(String domain) {
        this.domain = domain == null ? null : domain.trim();
    }

    public String getRemark() {
        return remark;
    }

    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}