package com.lee.oam.pojo;

import java.io.Serializable;

/**
 * 端口对应表@20160511
 * @author Administrator
 *
 */
public class OamIpport implements Serializable {
    /**
     * 主键
     *
     * @mbg.generated 2017-03-09 16:22:11
     */
    private String id;

    /**
     * IP�?
     *
     * @mbg.generated 2017-03-09 16:22:11
     */
    private String ip;

    /**
     * 服务器网�?
     *
     * @mbg.generated 2017-03-09 16:22:11
     */
    private String lan;

    /**
     * 交换机名�?
     *
     * @mbg.generated 2017-03-09 16:22:11
     */
    private String swit;

    /**
     * 端口�?
     *
     * @mbg.generated 2017-03-09 16:22:11
     */
    private String port;

    /**
     * 预留字段
     *
     * @mbg.generated 2017-03-09 16:22:11
     */
    private String ipid;

    /**
     * 序号
     *
     * @mbg.generated 2017-03-09 16:22:11
     */
    private Integer seq;

    /**
     * 备注
     *
     * @mbg.generated 2017-03-09 16:22:11
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table oam_ipport
     *
     * @mbg.generated 2017-03-09 16:22:11
     */
    private static final long serialVersionUID = 1L;

    /**
     * 主键
     *
     * @mbg.generated 2017-03-09 16:22:11
     */
    public String getId() {
        return id;
    }

    /**
     * 主键
     *
     * @param id java.lang.String
     *
     * @mbg.generated 2017-03-09 16:22:11
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * IP�?
     *
     * @mbg.generated 2017-03-09 16:22:11
     */
    public String getIp() {
        return ip;
    }

    /**
     * IP�?
     *
     * @param ip java.lang.String
     *
     * @mbg.generated 2017-03-09 16:22:11
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * 服务器网�?
     *
     * @mbg.generated 2017-03-09 16:22:11
     */
    public String getLan() {
        return lan;
    }

    /**
     * 服务器网�?
     *
     * @param lan java.lang.String
     *
     * @mbg.generated 2017-03-09 16:22:11
     */
    public void setLan(String lan) {
        this.lan = lan == null ? null : lan.trim();
    }

    /**
     * 交换机名�?
     *
     * @mbg.generated 2017-03-09 16:22:11
     */
    public String getSwit() {
        return swit;
    }

    /**
     * 交换机名�?
     *
     * @param swit java.lang.String
     *
     * @mbg.generated 2017-03-09 16:22:11
     */
    public void setSwit(String swit) {
        this.swit = swit == null ? null : swit.trim();
    }

    /**
     * 端口�?
     *
     * @mbg.generated 2017-03-09 16:22:11
     */
    public String getPort() {
        return port;
    }

    /**
     * 端口�?
     *
     * @param port java.lang.String
     *
     * @mbg.generated 2017-03-09 16:22:11
     */
    public void setPort(String port) {
        this.port = port == null ? null : port.trim();
    }

    /**
     * 预留字段
     *
     * @mbg.generated 2017-03-09 16:22:11
     */
    public String getIpid() {
        return ipid;
    }

    /**
     * 预留字段
     *
     * @param ipid java.lang.String
     *
     * @mbg.generated 2017-03-09 16:22:11
     */
    public void setIpid(String ipid) {
        this.ipid = ipid == null ? null : ipid.trim();
    }

    /**
     * 序号
     *
     * @mbg.generated 2017-03-09 16:22:11
     */
    public Integer getSeq() {
        return seq;
    }

    /**
     * 序号
     *
     * @param seq java.lang.Integer
     *
     * @mbg.generated 2017-03-09 16:22:11
     */
    public void setSeq(Integer seq) {
        this.seq = seq;
    }

    /**
     * 备注
     *
     * @mbg.generated 2017-03-09 16:22:11
     */
    public String getRemark() {
        return remark;
    }

    /**
     * 备注
     *
     * @param remark java.lang.String
     *
     * @mbg.generated 2017-03-09 16:22:11
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}