package com.lee.oam.pojo;

import java.io.Serializable;

import org.apache.commons.lang3.StringUtils;

public class OamIp implements Serializable {
    /**
     * 主键
     *
     * @mbg.generated 2017-02-28 10:28:36
     */
    private String id;

    /**
     * ip地址
     *
     * @mbg.generated 2017-02-28 10:28:36
     */
    private String ip;

    /**
     * 关联的设备ID
     *
     * @mbg.generated 2017-02-28 10:28:36
     */
    private String deviceId;

    /**
     * 掩码
     *
     * @mbg.generated 2017-02-28 10:28:36
     */
    private String mask;

    /**
     * 首选dns
     */
    private String dns1;

    /**
     * 备用dns
     */
    private String dns2;

    /**
     * 网关
     *
     * @mbg.generated 2017-02-28 10:28:36
     */
    private String gateway;

    /**
     * 备注
     *
     * @mbg.generated 2017-02-28 10:28:36
     */
    private String remark;

    private String createUser;

    private String createTime;

    private String updateUser;

    private String updateTime;

    /**
     * ip类型(公网 内网)
     */
    private String type;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table oam_ip
     *
     * @mbg.generated 2017-02-28 10:28:36
     */
    private static final long serialVersionUID = 1L;

    /**
     * 主键
     *
     * @mbg.generated 2017-02-28 10:28:36
     */
    public String getId() {
        return id;
    }

    /**
     * 主键
     *
     * @param id java.lang.String
     *
     * @mbg.generated 2017-02-28 10:28:36
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * ip地址
     *
     * @mbg.generated 2017-02-28 10:28:36
     */
    public String getIp() {
        return ip;
    }

    /**
     * ip地址
     *
     * @param ip java.lang.String
     *
     * @mbg.generated 2017-02-28 10:28:36
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * 关联的设备ID
     *
     * @mbg.generated 2017-02-28 10:28:36
     */
    public String getDeviceId() {
        return deviceId;
    }

    /**
     * 关联的设备ID
     *
     * @param deviceId java.lang.String
     *
     * @mbg.generated 2017-02-28 10:28:36
     */
    public void setDeviceId(String deviceId) {
        this.deviceId = deviceId == null ? null : deviceId.trim();
    }

    /**
     * 掩码
     *
     * @mbg.generated 2017-02-28 10:28:36
     */
    public String getMask() {
        return mask;
    }

    /**
     * 掩码
     *
     * @param mask java.lang.String
     *
     * @mbg.generated 2017-02-28 10:28:36
     */
    public void setMask(String mask) {
        this.mask = mask == null ? null : mask.trim();
    }

    public String getDns1() {
        return dns1;
    }

    public void setDns1(String dns1) {
        this.dns1 = dns1 == null ? null : dns1.trim();
    }

    public String getDns2() {
        return dns2;
    }

    public void setDns2(String dns2) {
        this.dns2 = dns2 == null ? null : dns2.trim();
    }

    /**
     * 网关
     *
     * @mbg.generated 2017-02-28 10:28:36
     */
    public String getGateway() {
        return gateway;
    }

    /**
     * 网关
     *
     * @param gateway java.lang.String
     *
     * @mbg.generated 2017-02-28 10:28:36
     */
    public void setGateway(String gateway) {
        this.gateway = gateway == null ? null : gateway.trim();
    }

    /**
     * 备注
     *
     * @mbg.generated 2017-02-28 10:28:36
     */
    public String getRemark() {
        return remark;
    }

    /**
     * 备注
     *
     * @param remark java.lang.String
     *
     * @mbg.generated 2017-02-28 10:28:36
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    public String getCreateUser() {
        return createUser;
    }

    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    public String getCreateTime() {
        return createTime;
    }

    public void setCreateTime(String createTime) {
        this.createTime = StringUtils.isBlank(createTime) ? null : createTime;
    }

    public String getUpdateUser() {
        return updateUser;
    }

    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    public String getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(String updateTime) {
        this.updateTime = StringUtils.isBlank(updateTime) ? null : updateTime;
    }

	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}
    
    
}