package com.lee.oam.pojo;

import java.io.Serializable;

/**
 * 专线资源明细
 * @author Administrator
 *
 */
public class OamLine implements Serializable {
    /**
     * 主键
     *
     * @mbg.generated 2017-03-09 15:18:57
     */
    private String id;

    /**
     * 端点名称
     *
     * @mbg.generated 2017-03-09 15:18:57
     */
    private String ddmc;

    /**
     * 线路编号
     *
     * @mbg.generated 2017-03-09 15:18:57
     */
    private String lxbh;

    /**
     * 本端IP
     *
     * @mbg.generated 2017-03-09 15:18:57
     */
    private String bdip;

    /**
     * 对端IP及其分支�?
     *
     * @mbg.generated 2017-03-09 15:18:57
     */
    private String ddip;

    /**
     * MSTP交换�?
     *
     * @mbg.generated 2017-03-09 15:18:57
     */
    private String mstpjhj;

    /**
     * �?��MSTP交换机VLAN
     *
     * @mbg.generated 2017-03-09 15:18:57
     */
    private String vlan;

    /**
     * MSTP交换机接�?
     *
     * @mbg.generated 2017-03-09 15:18:57
     */
    private String jhjjk;

    /**
     * 备注
     *
     * @mbg.generated 2017-03-09 15:18:57
     */
    private String bz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table oam_line
     *
     * @mbg.generated 2017-03-09 15:18:57
     */
    private static final long serialVersionUID = 1L;

    /**
     * 主键
     *
     * @mbg.generated 2017-03-09 15:18:57
     */
    public String getId() {
        return id;
    }

    /**
     * 主键
     *
     * @param id java.lang.String
     *
     * @mbg.generated 2017-03-09 15:18:57
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * 端点名称
     *
     * @mbg.generated 2017-03-09 15:18:57
     */
    public String getDdmc() {
        return ddmc;
    }

    /**
     * 端点名称
     *
     * @param ddmc java.lang.String
     *
     * @mbg.generated 2017-03-09 15:18:57
     */
    public void setDdmc(String ddmc) {
        this.ddmc = ddmc == null ? null : ddmc.trim();
    }

    /**
     * 线路编号
     *
     * @mbg.generated 2017-03-09 15:18:57
     */
    public String getLxbh() {
        return lxbh;
    }

    /**
     * 线路编号
     *
     * @param lxbh java.lang.String
     *
     * @mbg.generated 2017-03-09 15:18:57
     */
    public void setLxbh(String lxbh) {
        this.lxbh = lxbh == null ? null : lxbh.trim();
    }

    /**
     * 本端IP
     *
     * @mbg.generated 2017-03-09 15:18:57
     */
    public String getBdip() {
        return bdip;
    }

    /**
     * 本端IP
     *
     * @param bdip java.lang.String
     *
     * @mbg.generated 2017-03-09 15:18:57
     */
    public void setBdip(String bdip) {
        this.bdip = bdip == null ? null : bdip.trim();
    }

    /**
     * 对端IP及其分支�?
     *
     * @mbg.generated 2017-03-09 15:18:57
     */
    public String getDdip() {
        return ddip;
    }

    /**
     * 对端IP及其分支�?
     *
     * @param ddip java.lang.String
     *
     * @mbg.generated 2017-03-09 15:18:57
     */
    public void setDdip(String ddip) {
        this.ddip = ddip == null ? null : ddip.trim();
    }

    /**
     * MSTP交换�?
     *
     * @mbg.generated 2017-03-09 15:18:57
     */
    public String getMstpjhj() {
        return mstpjhj;
    }

    /**
     * MSTP交换�?
     *
     * @param mstpjhj java.lang.String
     *
     * @mbg.generated 2017-03-09 15:18:57
     */
    public void setMstpjhj(String mstpjhj) {
        this.mstpjhj = mstpjhj == null ? null : mstpjhj.trim();
    }

    /**
     * �?��MSTP交换机VLAN
     *
     * @mbg.generated 2017-03-09 15:18:57
     */
    public String getVlan() {
        return vlan;
    }

    /**
     * �?��MSTP交换机VLAN
     *
     * @param vlan java.lang.String
     *
     * @mbg.generated 2017-03-09 15:18:57
     */
    public void setVlan(String vlan) {
        this.vlan = vlan == null ? null : vlan.trim();
    }

    /**
     * MSTP交换机接�?
     *
     * @mbg.generated 2017-03-09 15:18:57
     */
    public String getJhjjk() {
        return jhjjk;
    }

    /**
     * MSTP交换机接�?
     *
     * @param jhjjk java.lang.String
     *
     * @mbg.generated 2017-03-09 15:18:57
     */
    public void setJhjjk(String jhjjk) {
        this.jhjjk = jhjjk == null ? null : jhjjk.trim();
    }

    /**
     * 备注
     *
     * @mbg.generated 2017-03-09 15:18:57
     */
    public String getBz() {
        return bz;
    }

    /**
     * 备注
     *
     * @param bz java.lang.String
     *
     * @mbg.generated 2017-03-09 15:18:57
     */
    public void setBz(String bz) {
        this.bz = bz == null ? null : bz.trim();
    }
}