package com.lee.oam.pojo;

import java.io.Serializable;

import org.apache.commons.lang3.StringUtils;

public class OamSoftAsset implements Serializable {
    /**
     * 主键
     *
     * @mbg.generated 2017-03-06 14:39:04
     */
    private String id;

    /**
     * 软件名称
     *
     * @mbg.generated 2017-03-06 14:39:04
     */
    private String softName;

    /**
     * 品牌
     *
     * @mbg.generated 2017-03-06 14:39:04
     */
    private String brand;

    /**
     * 购买个数
     *
     * @mbg.generated 2017-03-06 14:39:04
     */
    private Integer buyNum;

    /**
     * 是否已使�?
     *
     * @mbg.generated 2017-03-06 14:39:04
     */
    private String used;
    private String usedTitle;
    /**
     * 安装情况
     *
     * @mbg.generated 2017-03-06 14:39:04
     */
    private String installDetail;

    /**
     * 使用部门
     *
     * @mbg.generated 2017-03-06 14:39:04
     */
    private String deptId;
    private String deptName;
    /**
     * 客服电话
     *
     * @mbg.generated 2017-03-06 14:39:04
     */
    private String serviceTell;

    /**
     * 备注
     *
     * @mbg.generated 2017-03-06 14:39:04
     */
    private String remark;

    private String createUser;

    private String createTime;

    private String updateUser;

    private String updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table oam_soft_asset
     *
     * @mbg.generated 2017-03-06 14:39:04
     */
    private static final long serialVersionUID = 1L;

    /**
     * 主键
     *
     * @mbg.generated 2017-03-06 14:39:04
     */
    public String getId() {
        return id;
    }

    /**
     * 主键
     *
     * @param id java.lang.String
     *
     * @mbg.generated 2017-03-06 14:39:04
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * 软件名称
     *
     * @mbg.generated 2017-03-06 14:39:04
     */
    public String getSoftName() {
        return softName;
    }

    /**
     * 软件名称
     *
     * @param softName java.lang.String
     *
     * @mbg.generated 2017-03-06 14:39:04
     */
    public void setSoftName(String softName) {
        this.softName = softName == null ? null : softName.trim();
    }

    /**
     * 品牌
     *
     * @mbg.generated 2017-03-06 14:39:04
     */
    public String getBrand() {
        return brand;
    }

    /**
     * 品牌
     *
     * @param brand java.lang.String
     *
     * @mbg.generated 2017-03-06 14:39:04
     */
    public void setBrand(String brand) {
        this.brand = brand == null ? null : brand.trim();
    }

    /**
     * 购买个数
     *
     * @mbg.generated 2017-03-06 14:39:04
     */
    public Integer getBuyNum() {
        return buyNum;
    }

    /**
     * 购买个数
     *
     * @param buyNum java.lang.Integer
     *
     * @mbg.generated 2017-03-06 14:39:04
     */
    public void setBuyNum(Integer buyNum) {
        this.buyNum = buyNum;
    }

    /**
     * 是否已使�?
     *
     * @mbg.generated 2017-03-06 14:39:04
     */
    public String getUsed() {
        return used;
    }

    /**
     * 是否已使�?
     *
     * @param used java.lang.String
     *
     * @mbg.generated 2017-03-06 14:39:04
     */
    public void setUsed(String used) {
        this.used = used == null ? null : used.trim();
    }

    /**
     * 安装情况
     *
     * @mbg.generated 2017-03-06 14:39:04
     */
    public String getInstallDetail() {
        return installDetail;
    }

    /**
     * 安装情况
     *
     * @param installDetail java.lang.String
     *
     * @mbg.generated 2017-03-06 14:39:04
     */
    public void setInstallDetail(String installDetail) {
        this.installDetail = installDetail == null ? null : installDetail.trim();
    }

    /**
     * 使用部门
     *
     * @mbg.generated 2017-03-06 14:39:04
     */
    public String getDeptId() {
        return deptId;
    }

    /**
     * 使用部门
     *
     * @param deptId java.lang.String
     *
     * @mbg.generated 2017-03-06 14:39:04
     */
    public void setDeptId(String deptId) {
        this.deptId = deptId == null ? null : deptId.trim();
    }

    /**
     * 客服电话
     *
     * @mbg.generated 2017-03-06 14:39:04
     */
    public String getServiceTell() {
        return serviceTell;
    }

    /**
     * 客服电话
     *
     * @param serviceTell java.lang.String
     *
     * @mbg.generated 2017-03-06 14:39:04
     */
    public void setServiceTell(String serviceTell) {
        this.serviceTell = serviceTell == null ? null : serviceTell.trim();
    }

    /**
     * 备注
     *
     * @mbg.generated 2017-03-06 14:39:04
     */
    public String getRemark() {
        return remark;
    }

    /**
     * 备注
     *
     * @param remark java.lang.String
     *
     * @mbg.generated 2017-03-06 14:39:04
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    public String getCreateUser() {
        return createUser;
    }

    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    public String getCreateTime() {
        return createTime;
    }

    public void setCreateTime(String createTime) {
        this.createTime = StringUtils.isBlank(createTime)? null : createTime.trim();
    }

    public String getUpdateUser() {
        return updateUser;
    }

    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    public String getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(String updateTime) {
        this.updateTime = StringUtils.isBlank(updateTime) ? null : updateTime.trim();
    }

	public String getUsedTitle() {
		return usedTitle;
	}

	public void setUsedTitle(String usedTitle) {
		this.usedTitle = usedTitle;
	}

	public String getDeptName() {
		return deptName;
	}

	public void setDeptName(String deptName) {
		this.deptName = deptName;
	}
    
    
}