package com.lee.system.pojo;

import java.io.Serializable;

public class SysButton implements Serializable {
    /**
     * 主键
     *
     * @mbggenerated 2017-02-21 13:37:11
     */
    private String id;

    /**
     * 按钮名称
     *
     * @mbggenerated 2017-02-21 13:37:11
     */
    private String btnName;

    private String btnIcon;

    /**
     * 按钮参数
     *
     * @mbggenerated 2017-02-21 13:37:11
     */
    private String btnScript;

    /**
     * 菜单ID
     *
     * @mbggenerated 2017-02-21 13:37:11
     */
    private String menuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_button
     *
     * @mbggenerated 2017-02-21 13:37:11
     */
    private static final long serialVersionUID = 1L;

    /**
     * 主键
     *
     * @mbggenerated 2017-02-21 13:37:11
     */
    public String getId() {
        return id;
    }

    /**
     * 主键
     *
     * @param id java.lang.String
     *
     * @mbggenerated 2017-02-21 13:37:11
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * 按钮名称
     *
     * @mbggenerated 2017-02-21 13:37:11
     */
    public String getBtnName() {
        return btnName;
    }

    /**
     * 按钮名称
     *
     * @param btnName java.lang.String
     *
     * @mbggenerated 2017-02-21 13:37:11
     */
    public void setBtnName(String btnName) {
        this.btnName = btnName == null ? null : btnName.trim();
    }

    public String getBtnIcon() {
        return btnIcon;
    }

    public void setBtnIcon(String btnIcon) {
        this.btnIcon = btnIcon == null ? null : btnIcon.trim();
    }

    /**
     * 按钮参数
     *
     * @mbggenerated 2017-02-21 13:37:11
     */
    public String getBtnScript() {
        return btnScript;
    }

    /**
     * 按钮参数
     *
     * @param btnScript java.lang.String
     *
     * @mbggenerated 2017-02-21 13:37:11
     */
    public void setBtnScript(String btnScript) {
        this.btnScript = btnScript == null ? null : btnScript.trim();
    }

    /**
     * 菜单ID
     *
     * @mbggenerated 2017-02-21 13:37:11
     */
    public String getMenuId() {
        return menuId;
    }

    /**
     * 菜单ID
     *
     * @param menuId java.lang.String
     *
     * @mbggenerated 2017-02-21 13:37:11
     */
    public void setMenuId(String menuId) {
        this.menuId = menuId == null ? null : menuId.trim();
    }
}