package com.lee.system.pojo;

import java.io.Serializable;

import org.apache.commons.lang3.StringUtils;

public class SysFile implements Serializable {
    /**
     * 主键
     *
     * @mbg.generated 2017-03-07 09:30:28
     */
    private String id;

    /**
     * 文件�?
     *
     * @mbg.generated 2017-03-07 09:30:28
     */
    private String name;

    /**
     * 上传时间
     *
     * @mbg.generated 2017-03-07 09:30:28
     */
    private String uptime;

    /**
     * 上传人员
     *
     * @mbg.generated 2017-03-07 09:30:28
     */
    private String upuser;

    /**
     * 备注
     *
     * @mbg.generated 2017-03-07 09:30:28
     */
    private String remark;

    /**
     * 文件类型
     *
     * @mbg.generated 2017-03-07 09:30:28
     */
    private String type;
    private String typeTitle;
    /**
     * 文件路径
     */
    private String path;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_file
     *
     * @mbg.generated 2017-03-07 09:30:28
     */
    private static final long serialVersionUID = 1L;

    /**
     * 主键
     *
     * @mbg.generated 2017-03-07 09:30:28
     */
    public String getId() {
        return id;
    }

    /**
     * 主键
     *
     * @param id java.lang.String
     *
     * @mbg.generated 2017-03-07 09:30:28
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * 文件�?
     *
     * @mbg.generated 2017-03-07 09:30:28
     */
    public String getName() {
        return name;
    }

    /**
     * 文件�?
     *
     * @param name java.lang.String
     *
     * @mbg.generated 2017-03-07 09:30:28
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * 上传时间
     *
     * @mbg.generated 2017-03-07 09:30:28
     */
    public String getUptime() {
        return uptime;
    }

    /**
     * 上传时间
     *
     * @param uptime java.util.Date
     *
     * @mbg.generated 2017-03-07 09:30:28
     */
    public void setUptime(String uptime) {
        this.uptime = StringUtils.isBlank(uptime)?null:uptime;
    }

    /**
     * 上传人员
     *
     * @mbg.generated 2017-03-07 09:30:28
     */
    public String getUpuser() {
        return upuser;
    }

    /**
     * 上传人员
     *
     * @param upuser java.lang.String
     *
     * @mbg.generated 2017-03-07 09:30:28
     */
    public void setUpuser(String upuser) {
        this.upuser = upuser == null ? null : upuser.trim();
    }

    /**
     * 备注
     *
     * @mbg.generated 2017-03-07 09:30:28
     */
    public String getRemark() {
        return remark;
    }

    /**
     * 备注
     *
     * @param remark java.lang.String
     *
     * @mbg.generated 2017-03-07 09:30:28
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * 文件类型
     *
     * @mbg.generated 2017-03-07 09:30:28
     */
    public String getType() {
        return type;
    }

    /**
     * 文件类型
     *
     * @param type java.lang.String
     *
     * @mbg.generated 2017-03-07 09:30:28
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

	public String getPath() {
		return path;
	}

	public void setPath(String path) {
		this.path = path;
	}

	public String getTypeTitle() {
		return typeTitle;
	}

	public void setTypeTitle(String typeTitle) {
		this.typeTitle = typeTitle;
	}
    
    
}