package com.lee.system.pojo;

import java.io.Serializable;

public class SysPrivilege implements Serializable {
    /**
     * 主键
     *
     * @mbggenerated 2017-02-21 13:35:13
     */
    private String id;

    /**
     * 用户u 角色 r
     *
     * @mbggenerated 2017-02-21 13:35:13
     */
    private String masteru;

    /**
     * 用户或角色ID
     *
     * @mbggenerated 2017-02-21 13:35:13
     */
    private String masteruId;

    /**
     * no 不可�?yes 可用
     *
     * @mbggenerated 2017-02-21 13:35:13
     */
    private String enable;

    /**
     * 功能或者菜单id
     *
     * @mbggenerated 2017-02-21 13:35:13
     */
    private String buttonId;

    /**
     * 功能b或者菜单m
     *@mbggenerated 2017-02-21 13:35:13
     * @mbggenerated 2017-02-21 13:35:13
     */
    private String button;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_privilege
     *
     * @mbggenerated 2017-02-21 13:35:13
     */
    private static final long serialVersionUID = 1L;

    /**
     * 主键
     *
     * @mbggenerated 2017-02-21 13:35:13
     */
    public String getId() {
        return id;
    }

    /**
     * 主键
     *
     * @param id java.lang.String
     *
     * @mbggenerated 2017-02-21 13:35:13
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * 用户u 角色 r
     *
     * @mbggenerated 2017-02-21 13:35:13
     */
    public String getMasteru() {
        return masteru;
    }

    /**
     * 用户u 角色 r
     *
     * @param masteru java.lang.String
     *
     * @mbggenerated 2017-02-21 13:35:13
     */
    public void setMasteru(String masteru) {
        this.masteru = masteru == null ? null : masteru.trim();
    }

    /**
     * 用户或角色ID
     *
     * @mbggenerated 2017-02-21 13:35:13
     */
    public String getMasteruId() {
        return masteruId;
    }

    /**
     * 用户或角色ID
     *
     * @param masteruId java.lang.String
     *
     * @mbggenerated 2017-02-21 13:35:13
     */
    public void setMasteruId(String masteruId) {
        this.masteruId = masteruId == null ? null : masteruId.trim();
    }

    /**
     * no 不可�?yes 可用
     *
     * @mbggenerated 2017-02-21 13:35:13
     */
    public String getEnable() {
        return enable;
    }

    /**
     * no 不可�?yes 可用
     *
     * @param enable java.lang.String
     *
     * @mbggenerated 2017-02-21 13:35:13
     */
    public void setEnable(String enable) {
        this.enable = enable == null ? null : enable.trim();
    }

    /**
     * 功能id
     *
     * @mbggenerated 2017-02-21 13:35:13
     */
    public String getButtonId() {
        return buttonId;
    }

    /**
     * 功能id
     *
     * @param buttonId java.lang.String
     *
     * @mbggenerated 2017-02-21 13:35:13
     */
    public void setButtonId(String buttonId) {
        this.buttonId = buttonId == null ? null : buttonId.trim();
    }

	public String getButton() {
		return button;
	}

	public void setButton(String button) {
		this.button = button;
	}

    
}