package com.lee.system.pojo;

import java.io.Serializable;

public class SysRole implements Serializable {

	/**
	 * 主键
	 * @mbggenerated  2017-02-21 12:41:58
	 */
	private String id;
	/**
	 * 角色名称
	 * @mbggenerated  2017-02-21 12:41:58
	 */
	private String roleName;
	/**
	 * 排序序号
	 * @mbggenerated  2017-02-21 12:41:58
	 */
	private Integer roleDesc;
	/**
	 * 创建时间
	 * @mbggenerated  2017-02-21 12:41:58
	 */
	private String createTime;
	/**
	 * 备注
	 * @mbggenerated  2017-02-21 12:41:58
	 */
	private String remark;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table sys_role
	 * @mbggenerated  2017-02-21 12:41:58
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * 主键
	 * @mbggenerated  2017-02-21 12:41:58
	 */
	public String getId() {
		return id;
	}

	/**
	 * 主键
	 * @param id  java.lang.String
	 * @mbggenerated  2017-02-21 12:41:58
	 */
	public void setId(String id) {
		this.id = id == null ? null : id.trim();
	}

	/**
	 * 角色名称
	 * @mbggenerated  2017-02-21 12:41:58
	 */
	public String getRoleName() {
		return roleName;
	}

	/**
	 * 角色名称
	 * @param roleName  java.lang.String
	 * @mbggenerated  2017-02-21 12:41:58
	 */
	public void setRoleName(String roleName) {
		this.roleName = roleName == null ? null : roleName.trim();
	}

	/**
	 * 排序序号
	 * @mbggenerated  2017-02-21 12:41:58
	 */
	public Integer getRoleDesc() {
		return roleDesc;
	}

	/**
	 * 排序序号
	 * @param roleDesc  java.lang.Integer
	 * @mbggenerated  2017-02-21 12:41:58
	 */
	public void setRoleDesc(Integer roleDesc) {
		this.roleDesc = roleDesc;
	}

	/**
	 * 创建时间
	 * @mbggenerated  2017-02-21 12:41:58
	 */
	public String getCreateTime() {
		return createTime;
	}

	/**
	 * 创建时间
	 * @param createTime  java.util.Date
	 * @mbggenerated  2017-02-21 12:41:58
	 */
	public void setCreateTime(String createTime) {
		this.createTime = createTime.equals("") ? null : createTime;
	}

	/**
	 * 备注
	 * @mbggenerated  2017-02-21 12:41:58
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * 备注
	 * @param remark  java.lang.String
	 * @mbggenerated  2017-02-21 12:41:58
	 */
	public void setRemark(String remark) {
		this.remark = remark == null ? null : remark.trim();
	}
}