package com.lee.system.pojo;

import java.io.Serializable;

public class SysUserRole implements Serializable {
    /**
     * 主键
     *
     * @mbggenerated 2017-02-19 09:51:38
     */
    private String id;

    /**
     * 用户主键
     *
     * @mbggenerated 2017-02-19 09:51:38
     */
    private String userId;

    /**
     * 角色主键
     *
     * @mbggenerated 2017-02-19 09:51:38
     */
    private String roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_user_role
     *
     * @mbggenerated 2017-02-19 09:51:38
     */
    private static final long serialVersionUID = 1L;

    /**
     * 主键
     *
     * @mbggenerated 2017-02-19 09:51:38
     */
    public String getId() {
        return id;
    }

    /**
     * 主键
     *
     * @param id java.lang.String
     *
     * @mbggenerated 2017-02-19 09:51:38
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * 用户主键
     *
     * @mbggenerated 2017-02-19 09:51:38
     */
    public String getUserId() {
        return userId;
    }

    /**
     * 用户主键
     *
     * @param userId java.lang.String
     *
     * @mbggenerated 2017-02-19 09:51:38
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * 角色主键
     *
     * @mbggenerated 2017-02-19 09:51:38
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * 角色主键
     *
     * @param roleId java.lang.String
     *
     * @mbggenerated 2017-02-19 09:51:38
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId == null ? null : roleId.trim();
    }
}