package com.lee.system.pojo;

import java.io.Serializable;
import java.util.Set;

public class SysUser implements Serializable {
    private String id;

    /**
     * 登录名称
     *
     * @mbggenerated 2017-02-19 09:39:47
     */
    private String loginName;

    /**
     * 登录密码
     *
     * @mbggenerated 2017-02-19 09:39:47
     */
    private String loginPassword;

    /**
     * 部门ID
     *
     * @mbggenerated 2017-02-19 09:39:47
     */
    private String deptId;

    /**
     * 证实名称
     *
     * @mbggenerated 2017-02-19 09:39:47
     */
    private String realName;

    /**
     * 性别
     *
     * @mbggenerated 2017-02-19 09:39:47
     */
    private String sex;

    /**
     * 联系电话
     *
     * @mbggenerated 2017-02-19 09:39:47
     */
    private String phone;

    /**
     * 邮箱
     *
     * @mbggenerated 2017-02-19 09:39:47
     */
    private String email;

    private String qq;

    /**
     * 注册时间
     *
     * @mbggenerated 2017-02-19 09:39:47
     */
    private String createTime;

    /**
     * 备注
     *
     * @mbggenerated 2017-02-19 09:39:47
     */
    private String remark;
    
    /**是否启用*/
    private String enable;
    
    private String sexTitle;
    private String enableTitle;
    private String deptName;
    
    /**用户拥有的角色*/
    private Set<String> roles;
    /**用户拥有的权限*/
    private Set<String> Permissions;

    public String getEnable() {
		return enable;
	}

	public void setEnable(String enable) {
		this.enable = enable;
	}

	public Set<String> getRoles() {
		return roles;
	}

	public void setRoles(Set<String> roles) {
		this.roles = roles;
	}

	public Set<String> getPermissions() {
		return Permissions;
	}

	public void setPermissions(Set<String> permissions) {
		Permissions = permissions;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_user
     *
     * @mbggenerated 2017-02-19 09:39:47
     */
    private static final long serialVersionUID = 1L;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * 登录名称
     *
     * @mbggenerated 2017-02-19 09:39:47
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * 登录名称
     *
     * @param loginName java.lang.String
     *
     * @mbggenerated 2017-02-19 09:39:47
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName == null ? null : loginName.trim();
    }

    /**
     * 登录密码
     *
     * @mbggenerated 2017-02-19 09:39:47
     */
    public String getLoginPassword() {
        return loginPassword;
    }

    /**
     * 登录密码
     *
     * @param loginPassword java.lang.String
     *
     * @mbggenerated 2017-02-19 09:39:47
     */
    public void setLoginPassword(String loginPassword) {
        this.loginPassword = loginPassword == null ? null : loginPassword.trim();
    }

    /**
     * 部门ID
     *
     * @mbggenerated 2017-02-19 09:39:47
     */
    public String getDeptId() {
        return deptId;
    }

    /**
     * 部门ID
     *
     * @param deptId java.lang.String
     *
     * @mbggenerated 2017-02-19 09:39:47
     */
    public void setDeptId(String deptId) {
        this.deptId = deptId == null ? null : deptId.trim();
    }

    /**
     * 证实名称
     *
     * @mbggenerated 2017-02-19 09:39:47
     */
    public String getRealName() {
        return realName;
    }

    /**
     * 证实名称
     *
     * @param realName java.lang.String
     *
     * @mbggenerated 2017-02-19 09:39:47
     */
    public void setRealName(String realName) {
        this.realName = realName == null ? null : realName.trim();
    }

    /**
     * 性别
     *
     * @mbggenerated 2017-02-19 09:39:47
     */
    public String getSex() {
        return sex;
    }

    /**
     * 性别
     *
     * @param sex java.lang.Integer
     *
     * @mbggenerated 2017-02-19 09:39:47
     */
    public void setSex(String sex) {
        this.sex = sex;
    }

    /**
     * 联系电话
     *
     * @mbggenerated 2017-02-19 09:39:47
     */
    public String getPhone() {
        return phone;
    }

    /**
     * 联系电话
     *
     * @param phone java.lang.String
     *
     * @mbggenerated 2017-02-19 09:39:47
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * 邮箱
     *
     * @mbggenerated 2017-02-19 09:39:47
     */
    public String getEmail() {
        return email;
    }

    /**
     * 邮箱
     *
     * @param email java.lang.String
     *
     * @mbggenerated 2017-02-19 09:39:47
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    public String getQq() {
        return qq;
    }

    public void setQq(String qq) {
        this.qq = qq == null ? null : qq.trim();
    }

    /**
     * 注册时间
     *
     * @mbggenerated 2017-02-19 09:39:47
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * 注册时间
     *
     * @param createTime java.util.Date
     *
     * @mbggenerated 2017-02-19 09:39:47
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }

    /**
     * 备注
     *
     * @mbggenerated 2017-02-19 09:39:47
     */
    public String getRemark() {
        return remark;
    }

    /**
     * 备注
     *
     * @param remark java.lang.String
     *
     * @mbggenerated 2017-02-19 09:39:47
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

	public String getSexTitle() {
		return sexTitle;
	}

	public void setSexTitle(String sexTitle) {
		this.sexTitle = sexTitle;
	}

	public String getEnableTitle() {
		return enableTitle;
	}

	public void setEnableTitle(String enableTitle) {
		this.enableTitle = enableTitle;
	}

	public String getDeptName() {
		return deptName;
	}

	public void setDeptName(String deptName) {
		this.deptName = deptName;
	}
    
    
}